### ISSUE TITLE
Crashes when running

### ISSUE THREAD

**Issue by bahmutov** [ryardley/indexr#19]
Hi,

I just tried global installation and it choked

``` sh
$ npm install indexr -g
/Users/gleb/.nvm/versions/node/v6.3.1/bin/indexr -> /Users/gleb/.nvm/versions/node/v6.3.1/lib/node_modules/indexr/dist/bin.js
/Users/gleb/.nvm/versions/node/v6.3.1/lib
└─┬ indexr@1.1.1 
  ├─┬ async@2.0.1 
  │ └── lodash@4.15.0 
  ├─┬ babel-polyfill@6.13.0 
  │ ├── babel-runtime@6.11.6 
  │ ├── core-js@2.4.1 
  │ └── regenerator-runtime@0.9.5 
  ├── camelcase@3.0.0 
  ├── capitalize@1.0.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├─┬ glob@7.0.5 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.5 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.1 
  │ ├─┬ minimatch@3.0.3 
  │ │ └─┬ brace-expansion@1.1.6 
  │ │   ├── balanced-match@0.4.2 
  │ │   └── concat-map@0.0.1 
  │ ├── once@1.3.3 
  │ └── path-is-absolute@1.0.0 
  ├── linewrap@0.2.1 
  ├── lodash.curry@4.1.1 
  ├── lodash.flatten@4.4.0 
  ├── lodash.flow@3.5.0 
  ├── lodash.omit@4.5.0 
  ├── lodash.throttle@4.1.1 
  └── lodash.uniq@4.5.0 

~/git/utils on master*
$ indexr src
module.js:442
    throw err;
    ^

Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gleb/.nvm/versions/node/v6.3.1/lib/node_modules/indexr/dist/modules/watch/index.js:8:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by bahmutov** [comment]
node `v6.3.1` and npm `3.10.3`

**Comment by ryardley** [comment]
Thanks I think somehow a missing dep was hiding in the missing test coverage. Updating right now try v1.1.2.

**Comment by ryardley** [comment]
If it works for you please close the issue.
